interledger/open-payments

- README.md
Fixes #17 
This PR proposes to allow a JWT to be provided with the session creation request that identifies the "issuer" (user wallet/WM provider).
The WM extension (and in future the browser) can request JWTs from the provider up-front that are already bound to new session ids that haven't been used to create a session yet. This avoids a roundtrip to the provider when starting a new session.
The JWT is not bound to a destination website but in future this could be done by including an "aud" claim. (Need to consider privacy implications although this could be done in bulk to avoid correlating users to sites they visit).
When the website does a spend against the session the wallet MAY apply that spend to the pooled funds that have been sent by all users from a single provider.
> Add provider authentication

- open-api-spec.yaml
We decided not to pass STREAM receipts from the transport layer to the application layer. Instead, incoming payments serve as payment confirmation.
> chore: remove STREAM receipts from Open Payments OpenAPI spec

- .github/workflows/openapi.yaml
- .spectral.json
- open-api-spec.yaml
[`spectral`](https://github.com/stoplightio/spectral) appears to be more popular and caught errors/warnings missed by [`redocly/openapi-cli`](https://github.com/Redocly/openapi-cli).
Validation can be performed locally by running:
```
docker run --rm -it -v $(pwd):/tmp stoplight/spectral lint --ruleset "/tmp/.spectral.json" "/tmp/open-api-spec.yaml"
```
> chore: replace openapi validator

- auth-server-open-api-spec.yaml
- open-api-spec.yaml
https://spec.openapis.org/oas/v3.1.0#schema-object
>The `example` property has been deprecated in favor of the JSON Schema `examples` keyword. Use of `example` is discouraged, and later versions of this specification may remove it.
> chore: remove deprecated example field

- open-api-spec.yaml
Disallow additional properties.
Fix `ilpAddress` typo.
Note that `ilpApddress` and `sharedSecret` are optional since the same schema is used for getting and listing incoming payments.
Ideally those fields are required for the former (or potentially moved to their own endpoint).
> chore: specify required fields

- open-api-spec.yaml
This is needed for request validation both now and when the account id is removed from the `/{accountId}/incoming-payments/{id}` path (in order for the spec to distinguish between paths that do and do not include the account id).
> chore: define account id as path parameter

- auth-server-open-api-spec.yaml
> chore: make grant access identifier optional

- open-api-spec.yaml
- Consistent name for `id`
- OAS hack to provide descriptions on amount fields inside other schemas
> fix: stylistic tweaks for docs

- auth-server-open-api-spec.yaml
Updates the required response fields for `/introspect` on the auth server so that only `active` is required. This should match the implementation it has on [Rafiki](https://github.com/interledger/rafiki/blob/551eb5323876d2f111a7f36ebb0ae333710e8edb/packages/auth/src/accessToken/service.ts#L52-L73).
> fix: updated required fields for /introspect

- auth-server-open-api-spec.yaml
- add start and finish interaction endpoints
- start redirects to the identity server
- finish redirects to the client's finish url it specified on grant request
- fixes #139
> (feat): spec out interaction endpoints

- auth-server-open-api-spec.yaml
Remove `required` status from the `continue` field in the response from the `/continue` path.
[From the GNAP spec](https://datatracker.ietf.org/doc/html/draft-ietf-gnap-core-protocol#section-5.1) (emphasis mine):
> The grant response ([Section 3](https://datatracker.ietf.org/doc/html/draft-ietf-gnap-core-protocol#section-3)) MAY contain any newly-created access
tokens ([Section 3.2](https://datatracker.ietf.org/doc/html/draft-ietf-gnap-core-protocol#section-3.2)) or newly-released subject claims ([Section 3.4](https://datatracker.ietf.org/doc/html/draft-ietf-gnap-core-protocol#section-3.4)).
**The response MAY contain a new "continue" response ([Section 3.1](https://datatracker.ietf.org/doc/html/draft-ietf-gnap-core-protocol#section-3.1)) as
described above.**  The response SHOULD NOT …
> fix: change required fields for /continue

- auth-server-open-api-spec.yaml
The lack of the `quote` access type in the OpenAPI schema is blocking token introspection for Quote grants.
> feat: add quote to access schema

- auth-server-open-api-spec.yaml
The `key` field in the `/introspect` response is currently returning `nbf`, `exp`, `revoked` and `key_ops`, which isn't reflected in the OpenAPI spec yet.
> feat: add exp, nbf, revoked, key_ops to key schema

- auth-server-open-api-spec.yaml
- Removes the `identifier` property from `/grant/{id}/{nonce}` because `identifier` is a property of each `access` element rather than a top-level member
> fix(auth): remove separate identifier property

- auth-server-open-api-spec.yaml
Remove `limits-outgoing-recurring` schema
Enforce `sendAmount` and/or `receiveAmount` with `interval`
Disallow `interval` outside of `limits`
> fix: enforce amount with interval in outgoing payment limits

- auth-server-open-api-spec.yaml
- open-api-spec.yaml
Create receiver and interval schemas
- fixes #172 
- fixes #156
> chore: Add regex pattern for receiver

- auth-server-open-api-spec.yaml
Disallow `read` with `read-all`.
Disallow `list` with `list-all`.
Disallow duplicate actions.
- fixes #178
> chore: restrict access actions

- open-api-spec.yaml
We previously [renamed sub-resource ids](https://github.com/interledger/open-payments/pull/134) to `incomingPaymentId`, etc to disambiguate from the accompanying `accountId` path parameter.
`accountId` was removed in the [switch to payment pointers](https://github.com/interledger/open-payments/pull/145), and sub-resource ids are now the lone path parameters.
This makes path parameters consistent with the [auth server spec](https://github.com/interledger/open-payments/blob/6b5c088b71dd354139d5140c1a57aba6f7c9838e/auth-server-open-api-spec.yaml#L168).
- inspired by addition of reusable parameter definitions in #187
> chore: add shared sub-resource id path parameter

- auth-server-open-api-spec.yaml
Some server frameworks (i.e. Koa) also include a string body in the response of its native redirect function. This will make such responses passable in the OpenAPI spec.
> feat: set response body for redirects to string

- .github/workflows/publish-openapi.yaml
The `rdme` cli appears to resolve relative paths (to the shared schemas file) based on the working directory instead of the file path itself.
Use `rdme`'s  [`--workingDirectory`](https://github.com/readmeio/rdme#override-the-working-directory)
- fixes #199 
This was tested here:
https://github.com/interledger/open-payments/commits/bw-test-fix
> fix: specify working directory for rdme publish

- openapi/AS/IdP/openapi.yaml
- openapi/AS/RS/openapi.yaml
- openapi/AS/client/openapi.yaml
- openapi/RS/openapi.yaml
- openapi/shared/schemas.yaml
There is an open [Rafiki PR](https://github.com/interledger/rafiki/pull/669) that generates Typescript types from the Open API spec using the [openapi-typescript](https://github.com/drwpow/openapi-typescript) package. 
Whenever type generation script runs, it generates a file with types as such:
```ts
export interface paths {
...
}
export interface components {
schemas: {
...
}
responses: {
...
}
parameters: {
...
}
}
export interface operations {
...
}
export interface external {
...
}
```
The `external` interface is the one that holds references to the types for when an external `$ref` is used in a spec (e.g. `$ref: ../shared/schemas.yaml#/amount`. 
However, after the spec split, the type generation for the resource server failed to populate this `external` interface, since …
> chore: update shared schema spec for consistency

- openapi/AS/IdP/openapi.yaml
Specifies the possible values of the redirect response body for interaction completion like was previously done for the interaction start response.
> feat: specify redirect body for finishing interactions

- openapi/schemas.yaml
Addresses (but doesn't really fix) https://github.com/interledger/rafiki/issues/630. This spec is less strict to allow valid responses from the AS to pass validation, but is a bit too loose for what we actually want to achieve with it. The main restriction that this doesn't cover is:
* The spec does not restrict a grant to (at most) one of each `type` of access.
> feat: use nullable limits and openapi-compliant uniqueness for access schema

- openapi/schemas.yaml
Remove `allof` since it is unsupported by OpenAPI. Right now it's essentially functioning like a `oneOf`, where certain items are _required_ to be in a list of `actions`.  Is a band-aid fix for https://github.com/interledger/rafiki/issues/630 - it doesn't address the core issue.
> feat: remove allof

- .github/workflows/publish-openapi.yaml
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
> fix: move workflow_run in publish action

- openapi/resource-server.yaml
Fixes #227 
_Copied from #227 description:_
The Open Payments API doc examples prepend the `pagination` parameter when showing an example call to list outgoing or incoming payments:
Specifically,
```sh
curl --request GET \
--url 'https://openpayments.guide/alice/incoming-payments?pagination=first=10&cursor=uuid' \
--header 'accept: application/json'
// inclusion of "pagination" is the issue here    
```
https://docs.openpayments.guide/reference/list-outgoing-payments
However, we do not use root `pagination` parameter when we parse the query parameters when we are handling `GET /(incoming | outgoing)-payments` calls in `backend`, we only look at `first` `last` `cursor` params:
https://github.com/interledger/rafiki/blob/a0302b390192f001fc4baa6bc55ae8dcfb13143a/packages/backend/src/open_payme …
> feat: add form style to pagination params

- openapi/auth-server.yaml
- Adds `401` as a potential response from the grant initiation endpoint.
Because this endpoint uses httpsig validation, the spec should account for `Unauthorized` responses.
> feat: add unauthorized response to grant initiation

- openapi/resource-server.yaml
- Don't define pagination query parameters as object
Existing OpenAPI 3.1 Node.js tooling cannot explode to individual parameters.
Enforce mutually exclusive validation, etc in the RS.
- https://github.com/interledger/rafiki/issues/443
> don't define pagination query parameters as object

- openapi/resource-server.yaml
We currently have descriptions for incoming and outgoing payments on 
Readme.io which are outdated. I pulled in all the info that is still valid such that we can remove the outdated docs from Readme.io
> docs: move info from readme into spec

- .changeset/khaki-spies-tan.md
- openapi/resource-server.yaml
- packages/open-payments/README.md
- packages/open-payments/src/client/incoming-payment.test.ts
- packages/open-payments/src/client/outgoing-payment.test.ts
- packages/open-payments/src/openapi/generated/resource-server-types.ts
- packages/open-payments/src/test/helpers.ts
- adds `metadata` field to incoming/outgoing payment routes
First of several PRs for #221 (add metadata to spec, implement metadata field in rafiki, remove `description`/`externalRef`)
> feat: add  metadata field to payments

- .changeset/metal-panthers-fix.md
- .github/workflows/lint-test-build.yaml
- openapi/resource-server.yaml
- packages/open-payments/src/openapi/generated/resource-server-types.ts
- Making `startCursor` and `endCursor` optional in the resource server spec for pagination responses.
- Adding CI check for missing generated types in the open-payments client
- Fixes #191 
When there are no results, it makes sense for `startCursor` and `endCursor` to be nullable:
- https://github.com/interledger/open-payments/issues/191#issuecomment-1579003465
This is actually causing an error in Rafiki when making Open Payments requests to list incoming/outgoing payments, and there are no results.
See the new changes here: https://open-payments-integration.readme.io/v1.1/reference/list-incoming-payments
> chore: make startCursor and endCursor optional

- .changeset/cold-owls-attack.md
- openapi/resource-server.yaml
- packages/open-payments/README.md
- packages/open-payments/src/client/incoming-payment.test.ts
- packages/open-payments/src/client/outgoing-payment.test.ts
- packages/open-payments/src/openapi/generated/resource-server-types.ts
- packages/open-payments/src/test/helpers.ts
- packages/openapi/src/middleware.test.ts
- Removes `externalRef` and `description` fields from payments (breaking change)
- Major version bump of `open-payments`
Fixes: #221
> chore: remove deprecated payment fields

- .changeset/tender-ravens-breathe.md
- openapi/auth-server.yaml
- openapi/resource-server.yaml
- openapi/schemas.yaml
- packages/open-payments/README.md
- packages/open-payments/src/client/outgoing-payment.test.ts
- packages/open-payments/src/client/outgoing-payment.ts
- packages/open-payments/src/openapi/generated/auth-server-types.ts
- packages/open-payments/src/openapi/generated/resource-server-types.ts
- packages/open-payments/src/test/helpers.ts
- packages/open-payments/src/types.ts
- updates resource server spec and auth server spec to change `sendAmount` to `debitAmount`
We originally planned to add fees to the OP resources, however, we decided that fees should be included in the `debitAmount`. The difference in `debitAmount - receiveAmount` can be considered being the fees. The ASE may list those fees separately on the consent screen displayed to the user. 
- fixes #274
> feat: add properties for quoting

- .changeset/six-hounds-dress.md
- packages/http-signature-utils/package.json
- pnpm-lock.yaml
Specify the version of `httpbis-digest-headers` in order to fetch it from the NPM registry instead of GitHub. 
- https://github.com/interledger/rafiki/pull/1795#issuecomment-1698607385
> chore(deps): pin `httpbis-digest-headers` version

- .changeset/rare-dragons-sing.md
- packages/open-payments/src/types.ts
- Making `interact` property optional in grant requests for the open payments client to correctly match the Open Payments spec
Fixes #281
> feat: making interact property optional for grant requests

- .changeset/thick-deers-sell.md
- packages/http-signature-utils/README.md
- packages/http-signature-utils/src/index.ts
- packages/http-signature-utils/src/utils/key.test.ts
- packages/http-signature-utils/src/utils/key.ts
Adds `loadBase64Key` to http-signature-utils
> feat(http-signature-utils): add functionality to load a base64 encoded private key

- .changeset/loud-snakes-melt.md
- openapi/auth-server.yaml
- openapi/resource-server.yaml
- adds `rafiki.money` as base path
- fixes https://github.com/interledger/open-payments/issues/303
The issues suggests maybe using rafiki.money as the base url but I opted for openpayments.guide because that's what it originally was. https://github.com/interledger/open-payments/blob/5d39b2ef5f202e6378555b790730f9465ecd6f97/openapi/resource-server.yaml#L35C3-L39 This makes the base url consistent with existing examples.
> fix(openapi): add base url

- .changeset/clean-mice-sparkle.md
- openapi/resource-server.yaml
- openapi/schemas.yaml
- packages/open-payments/src/client/grant.ts
- packages/open-payments/src/client/incoming-payment.test.ts
- packages/open-payments/src/client/incoming-payment.ts
- packages/open-payments/src/client/index.ts
- packages/open-payments/src/client/outgoing-payment.test.ts
- packages/open-payments/src/client/outgoing-payment.ts
- packages/open-payments/src/client/quote.test.ts
- packages/open-payments/src/client/quote.ts
- packages/open-payments/src/client/token.ts
- packages/open-payments/src/client/wallet-address.ts
- packages/open-payments/src/openapi/generated/auth-server-types.ts
- packages/open-payments/src/openapi/generated/resource-server-types.ts
- packages/open-payments/src/types.ts
- packages/openapi/src/middleware.test.ts
* Adds the walletAddress field to request bodies for:
* `POST /outgoing-payments`
* `POST /incoming-payments`
* `POST /incoming-payments/{id}/complete`
* Adds the wallet-address query parameter to requests for:
* `GET /incoming-payments/{id}`
* `GET /outgoing-payments/{id}`
* `GET /incoming-payments`
* `GET /outgoing-payments`
Fixes #304.
> feat: add wallet address to subresource requests

- .changeset/cyan-jokes-travel.md
- packages/open-payments/src/types.ts
- Our `PaginationArgs` type was assuming all `list-incoming-payments` query params were for pagination. After adding the `wallet-address` param this broke our `PaginationArgs` type so I changed to just explicitly use the pagination specific parameters.
- fixes: https://github.com/interledger/rafiki/issues/2070
> fix(open-payments): limit pagination args to relevant params

- .changeset/lazy-penguins-roll.md
- openapi/resource-server.yaml
- packages/open-payments/src/client/index.ts
- packages/open-payments/src/openapi/generated/resource-server-types.ts
- packages/open-payments/src/test/helpers.ts
- adds authSever to the return type of public-incoming-payment in the openapi spec and updates our client accordingly (updated tests, generated type, fixed `AuthenticatedClient` type issue introduced by requiring `authServer`).
- progress towards https://github.com/interledger/rafiki/issues/2119
> feat(open-payments): add authServer to public incoming payment return type

- .changeset/silent-forks-rescue.md
- openapi/resource-server.yaml
- packages/openapi/src/middleware.test.ts
- removes the defaults which are setting both first and last in the validator middleware, which causes our list lookup to fail because it doesnt expect both
progress towards https://github.com/interledger/rafiki/issues/2116
This works, but I'm actually not sure if this is ultimately the best way and wonder if we might want to tweak it later. It seems like we may have had default parameters in the past without this same issue?
> fix(openapi): rm first last param defaults

- .changeset/chilly-days-repeat.md
- packages/open-payments/src/index.ts
- exports public incoming payment mock, type
while working on the receiver service tests in https://github.com/interledger/rafiki/pull/2122 I discovered these needed to be exported
> fix(open-payments): exports public incoming payment mock, type

- docs/src/content/docs/snippets/grant-continue.mdx
- docs/src/content/docs/snippets/grant-create.mdx
- docs/src/content/docs/snippets/grant-revoke.mdx
- docs/src/content/docs/snippets/incoming-complete.mdx
- docs/src/content/docs/snippets/incoming-create.mdx
- docs/src/content/docs/snippets/incoming-get.mdx
- docs/src/content/docs/snippets/incoming-list.mdx
- docs/src/content/docs/snippets/outgoing-create.mdx
- docs/src/content/docs/snippets/outgoing-get.mdx
- docs/src/content/docs/snippets/outgoing-list.mdx
- docs/src/content/docs/snippets/quote-create.mdx
- docs/src/content/docs/snippets/quote-get.mdx
- docs/src/content/docs/snippets/token-revoke.mdx
- docs/src/content/docs/snippets/token-rotate.mdx
- docs/src/content/docs/snippets/wallet-get-info.mdx
- docs/src/content/docs/snippets/wallet-get-keys.mdx
This PR fixes the issue where the link out icon appears twice for "View full source" links. This is due to prettier introducing an extra element.
N/A
> fix: duplicate link out icon issue

- .changeset/ninety-beans-do.md
- openapi/auth-server.yaml
- packages/open-payments/src/client/grant.ts
- packages/open-payments/src/types.ts
Makes the `access_token` field optional for `POST /continue/{id}` on the authorization server Open Payments SDK.
Fixes #385 
Allows the continue endpoint for an authorization server to be polled for interaction completion.
> feat: make access_token optional in /continue response in SDK

- .changeset/modern-cups-develop.md
- packages/open-payments/src/client/grant.ts
- packages/open-payments/src/client/index.ts
Updates the wallet address route validators to pull from the wallet address spec instead of the resource server spec.
Fixes #396.
When `@interledger/open-payments` at 6.2.0 and onward gets imported, it fails to create the route validators for wallet addresses. The reason for this is that the routes for wallet addresses were moved from the resource server spec, which the validators were still trying to pull from, to a separate wallet address server spec. So the routes were no longer being found when seeking them in the resource server spec.
> fix: pull in correct openapi spec for wallet address routes in sdk

- docs/src/content/docs/introduction/grants.mdx
- docs/src/content/docs/introduction/op-concepts.mdx
- docs/src/content/docs/snippets/wallet-get-keys.mdx
- docs/src/drafts/resources/glossary.mdx
> docs: minor content updates

- docs/src/content/docs/guides/make-onetime-payment.mdx
- docs/src/content/docs/guides/make-recurring-payments.mdx
- docs/src/content/docs/snippets/wallet-get-info.mdx
- docs/src/content/docs/snippets/wallet-get-keys.mdx
Update wallet address links to point to the wallet address server (instead of the old resource server)
> chore: update wallet address links

- .changeset/light-rabbits-rhyme.md
- packages/http-signature-utils/package.json
- packages/http-signature-utils/src/index.ts
- packages/http-signature-utils/src/utils/signatures.test.ts
- packages/http-signature-utils/src/utils/signatures.ts
- packages/http-signature-utils/src/utils/validation.test.ts
- packages/http-signature-utils/src/utils/validation.ts
- packages/open-payments/src/client/requests.test.ts
- pnpm-lock.yaml
Update `http-message-signatures` to its latest version and fix breaking changes.
Closes #420.
> feat(sig-utils): upgrade `http-message-signatures` to the most recent version

- .changeset/fuzzy-rivers-jog.md
- openapi/auth-server.yaml
- openapi/schemas.yaml
- packages/open-payments/src/openapi/generated/auth-server-types.ts
- packages/open-payments/src/openapi/generated/resource-server-types.ts
- packages/open-payments/src/openapi/generated/wallet-address-server-types.ts
- packages/openapi/src/middleware.test.ts
changes the receiver regex so that:
-  it now matches with `http` and any id (instead of just uuid)
-  it does not match with deprecated `/connections/` path
I noticed when using the client in the local environment that a receiver with an `http` url fails validation, which is necessary for local development. We are already using such a url, we're just not using the client for it (see the bruno/postman `Create Quote` request body). Widening that was the main goal and the other changes are more cleanup.
fixes https://github.com/interledger/open-payments/issues/429
> feat: update receiver regex validation

- .changeset/olive-eagles-talk.md
- packages/open-payments/src/client/grant.test.ts
- packages/open-payments/src/client/grant.ts
- packages/open-payments/src/types.ts
Updates the client args so that the continue request does not require the `interact_ref` nor `body`. It was recently changed such that it can be undefined, but is still required like so:
```ts
client.grant.continue({ accessToken, url }, { interact_ref: undefined })
```
With these changes you can do:
```ts
client.grant.continue({ accessToken, url }, {})
```
or
```ts
client.grant.continue({ accessToken, url })
```
small follow-up on https://github.com/interledger/open-payments/issues/433
Originally I made the PR for ergonomics sake on the client, but actually I think it will be necessary for continuation polling via the client (at least without adjusting auth server logic), since this is how we're checking whether or not to poll (condition wont be met with any `body.interact_ref`):
```ts
if …
```
> feat: make body, interact_ref optional on client grant continue

- .changeset/tasty-spoons-pay.md
- packages/open-payments/src/client/requests.ts
- packages/open-payments/src/test/helpers.ts
- packages/openapi/README.md
- packages/openapi/src/index.ts
- packages/openapi/src/middleware.test.ts
- packages/openapi/src/middleware.ts
Changes to the `createValidatorMiddleware` behaviour in `packages/openapi`:
- The middleware now throws a `OpenAPIValidatorMiddlewareError` instead of directly using Koa's `ctx.throw` function. This error class has `message` and `status` properties that describe the exact validation error as well as the status code that should be thrown.
- The middleware now takes in an optional `validationOptions` argument that determines whether to validate just the request, the response or both. By default, both are validated, and the middleware no longer uses `process.env.NODE_ENV` to determine whether to validate the response or not.
Fixes #445
> feat(openapi): throw OpenAPIValidatorMiddlewareError

- .changeset/lazy-phones-sniff.md
- packages/openapi/src/index.ts
- Exporting out `OpenAPIValidatorMiddlewareError` from `openapi` package, forgot to do so in previous PR 🙃 
related to #445
> chore(openapi): export OpenAPIValidatorMiddlewareError

- docs/src/content/docs/introduction/op-concepts.mdx
Fix in outgoing payment. Payer needs to add consent not payee.
No context
> docs(concepts): typo

- .changeset/friendly-dryers-search.md
- .prettierrc.yaml
- docs/src/content/docs/introduction/op-concepts.mdx
- openapi/resource-server.yaml
- packages/open-payments/src/client/outgoing-payment.test.ts
- packages/open-payments/src/openapi/generated/resource-server-types.ts
- changes spec and test to allow createing outgoing payment  from `incomingPaymentId`/`debitAmount` instead of only `quoteId`
fixes https://github.com/interledger/open-payments/issues/415
> feat: add option to create outgoing payment from incoming payment

- docs/package.json
- pnpm-lock.yaml
This PR bumps dependencies to the latest version, including the [0.22.0](https://github.com/withastro/starlight/blob/main/packages/starlight/CHANGELOG.md#0220) version of Starlight that includes synced tabs. Reviewed the changelog and the potential breaking changes do not affect our implementation.
Might close #352
> chore: bump dependencies to latest versions

- docs/astro.config.mjs
- docs/src/content/docs/resources/get-involved.mdx
> Added Santosh's 'Get involved' page

- docs/src/content/docs/introduction/op-flow.mdx
> Update large sequence diagram

- docs/src/content/docs/snippets/grant-continue.mdx
- docs/src/content/docs/snippets/grant-create.mdx
- docs/src/content/docs/snippets/grant-revoke.mdx
- docs/src/content/docs/snippets/incoming-complete.mdx
- docs/src/content/docs/snippets/incoming-create.mdx
- docs/src/content/docs/snippets/incoming-get.mdx
- docs/src/content/docs/snippets/incoming-list.mdx
- docs/src/content/docs/snippets/outgoing-create.mdx
- docs/src/content/docs/snippets/outgoing-get.mdx
- docs/src/content/docs/snippets/outgoing-list.mdx
- docs/src/content/docs/snippets/quote-create.mdx
- docs/src/content/docs/snippets/quote-get.mdx
- docs/src/content/docs/snippets/token-revoke.mdx
- docs/src/content/docs/snippets/token-rotate.mdx
- docs/src/content/docs/snippets/wallet-get-info.mdx
- docs/src/content/docs/snippets/wallet-get-keys.mdx
- docs/src/partials/js-prerequisites.mdx
As the title says, this adds JS code snippets to the docs. We need it for the UCT hack week. The snippets themselves are the same, only the prerequisites and the run command changed. Plus the link the the full snippet.
> chore: add JS tab to code snippets

- .changeset/shy-needles-brush.md
- openapi/resource-server.yaml
- packages/open-payments/src/client/outgoing-payment.test.ts
- packages/open-payments/src/openapi/generated/resource-server-types.ts
- packages/open-payments/src/test/helpers.ts
- packages/open-payments/src/types.ts
- changes `POST /outgoing-payment` return type to new `outgoing-payment-with-spent-amounts` which extends existing `outgoing-payment` with new required fields `grantSpentDebitAmount` and `grantSpentReceiveAmount`.
fixes: https://github.com/interledger/open-payments/issues/469
progress towards: https://github.com/interledger/rafiki/issues/2678
> feat: return outgoing-payment-with-spent-amounts from POST /outgoing-payment

- .changeset/little-lobsters-yell.md
- packages/open-payments/src/index.ts
exports `OutgoingPaymentWithSpentAmounts`  type
missed in  https://github.com/interledger/open-payments/pull/474
> chore: export OutgoingPaymentWithSpentAmounts

- .changeset/warm-geese-rescue.md
- packages/open-payments/README.md
- packages/open-payments/src/client/error.ts
- packages/open-payments/src/client/index.test.ts
- packages/open-payments/src/client/outgoing-payment.test.ts
- packages/open-payments/src/client/requests.test.ts
- packages/open-payments/src/client/requests.ts
Now that we are returning the following error response from the AS:
```json
{
"error": {
"code": "invalid_client",
"description": "could not determine client"
}
}
```
we now populate `code` and `description` fields in the `OpenPaymentsClientError` with the correct values.
- Fixes #482
> chore(open-payments): parse error objects, and return error codes

- .changeset/eight-cups-reflect.md
- packages/open-payments/src/client/outgoing-payment.ts
- updates return type of create outgoing payment method on the open payments client
fixes issue raised in this comment: https://github.com/interledger/open-payments/pull/480#issuecomment-2202353862
looks like it was probably first encountered here https://github.com/interledger/web-monetization-extension/pull/386/files
> fix(open-payments): change outgoingPayment.create return type

- .changeset/grumpy-fireants-jump.md
- packages/openapi/package.json
- pnpm-lock.yaml
Update `@apidevtools/json-schema-ref-parser` package in `openapi` in order to fix an issue where the client wouldn't be able to parse the API specs in Windows due to:
- https://github.com/APIDevTools/json-schema-ref-parser/issues/311
Fixes #505
> chore: fix windows file parsing when loading OpenAPI specs

- docs/astro.config.mjs
- docs/src/content/docs/index.mdx
Added an Umami site tracking script so that we can record page visits for the Open Payments docs.
This gets the basic infrastructure in place and allows us to track page views. There will be more work needed to add granular event tracking based on clicking links.
> feat: added basic site tracking using Umami

- docs/README.md
- docs/src/content/docs/snippets/grant-continue.mdx
- docs/src/content/docs/snippets/grant-create.mdx
- docs/src/content/docs/snippets/grant-revoke.mdx
- docs/src/content/docs/snippets/incoming-complete.mdx
- docs/src/content/docs/snippets/incoming-create.mdx
- docs/src/content/docs/snippets/incoming-get.mdx
- docs/src/content/docs/snippets/incoming-list.mdx
- docs/src/content/docs/snippets/outgoing-create.mdx
- docs/src/content/docs/snippets/outgoing-list.mdx
- docs/src/content/docs/snippets/quote-create.mdx
- docs/src/content/docs/snippets/quote-get.mdx
- docs/src/content/docs/snippets/wallet-get-keys.mdx
- docs/src/partials/code-snippets-template.mdx
- docs/src/partials/js-prerequisites.mdx
- docs/src/partials/ts-prerequisites.mdx
- Replace disclosure component with details tag in ts-prerequisites and js-prerequisites
- Remove Disclosure import from mdx files
- Remove references to Disclosure component in README.md and code-snippets-template.mdx
> docs: mi/50/details-component

- docs/package.json
- pnpm-lock.yaml
This PR bumps the docs dependencies to the latest versions. Tested locally to ensure that upgrade to Starlight 0.30.0 and Astro 5 did not break anything.
> chore: bump docs dependencies to the latest versions

- docs/src/content/docs/snippets/grant-continue.mdx
Adds the additional step for grant continuation that was missing in the docs and snippet, where we check if the grant is finalized.
> fix(docs): add additonal step for grant continuation

- docs/src/partials/js-prerequisites.mdx
- docs/src/partials/ts-prerequisites.mdx
Update Node version to 20 in typescript and javascript partials.
> docs: mi/538/update-node-version

- docs/src/content/docs/guides/make-recurring-payments.mdx
Added note that rotating a token is only necessary when the previous token has expired.
> docs: mi/update-recurring-payments-guide

- .github/workflows/deploy-docs.yaml
- docs/package.json
- pnpm-lock.yaml
This PR bumps dependencies for the Open Payments documentation site and updates the Github actions to their latest versions
> chore: dependency bumps and ci updates

- .changeset/plenty-cooks-mix.md
- openapi/auth-server.yaml
- packages/open-payments/src/openapi/generated/auth-server-types.ts
- Adds a `gnap-error` schema to the spec, and references them in the error responses of the auth server endpoint specs.
Closes #518.
> feat: add gnap error response schema to spec

- openapi/wallet-address-server.yaml
- packages/open-payments/src/openapi/generated/wallet-address-server-types.ts
Adds redirect response code to payment pointer url
Acomodates feature https://github.com/interledger/rafiki/issues/3268 to redirect to webpage when querying payment pointer in browser
> feat: add wallet redirect response code

- .changeset/fuzzy-parrots-yawn.md
- package.json
- packages/http-signature-utils/package.json
- packages/open-payments/package.json
- packages/open-payments/src/client/requests.ts
- packages/openapi/package.json
- pnpm-lock.yaml
- tsconfig.build.json
- Upgrading typescript to 5.8.2
Fixes #568
> chore: upgrade typescript to v5

- .changeset/red-dryers-poke.md
- openapi/auth-server.yaml
- openapi/resource-server.yaml
- openapi/wallet-address-server.yaml
- packages/open-payments/package.json
- packages/open-payments/src/openapi/generated/auth-server-types.ts
- packages/open-payments/src/openapi/generated/resource-server-types.ts
- packages/open-payments/src/openapi/generated/wallet-address-server-types.ts
- packages/open-payments/src/types.ts
- pnpm-lock.yaml
- Updating `openapi-typescript` to latest version
- Making `requestBody` required in grant request (to generate correct types)
- Adding `additionalProperties: true` in spec where necessary
Fixes #249
> chore: update openapi-typescript

- .changeset/grumpy-clouds-shave.md
- openapi/resource-server.yaml
- packages/open-payments/src/openapi/generated/resource-server-types.ts
- Add `additionalProperties: true` in incoming payment creation request body to allow proper type generation in the client
https://github.com/interledger/open-payments/pull/567#discussion_r2024473497
Related to #249
> chore(open-payments): update incoming payment metadata type

- packages/http-signature-utils/README.md
Fix examples syntax.
`validateSignatureHeaders(request: {` is not validate function call syntax. Copy pasting examples will lead to syntax errors.
> docs(http-signature-utils): fix syntax in examples

- .changeset/beige-grapes-brush.md
- docs/src/content/docs/guides/split-payments.mdx
- packages/open-payments/README.md
- Updating client README to
- Replacing `new URL(customerWalletAddress.id).origin` to use eg. `customerWalletAddress.resourceServer` directly
- Making sure we are not providing both `receiveAmount` and `debitAmount` in the same grant outgoing payment request, as that is no longer possible
- Updating split payments doc
- use customerWalletAddress.resourceServer directly instead of e.g. URL(customerWalletAddress.id).origin
- updating variable names to be more clear about what is used where
Fixes #615
> chore: update client usage in readme & docs

- docs/src/content/docs/overview/getting-started.mdx
- docs/src/content/docs/resources/glossary.mdx
- docs/src/content/docs/sdk/before-you-begin.mdx
- docs/src/partials/before-you-begin.mdx
- Revised "Getting Started" to introduce the OP SDKs and clarify their role
- Renamed "Test Wallet" title to "Before you begin" to match the left nav
- Updated "Before you Begin" content to introduce the SDKs and how to use the SDK snippet pages, including the consistent page structure across snippets
- Update link in "Before you Begin" partial to the test wallet section
- Updated "Open Payments (OP)" term in the Glossary to include a brief mention of the SDKs
Fixes [OP 613](https://github.com/interledger/open-payments/issues/613)
> docs: differentiate API and SDK content

- docs/package.json
- docs/src/components/ChunkedSnippet.astro
- docs/src/styles/openpayments.css
- pnpm-lock.yaml
This PR:
- bumps dependencies to the latest versions, including the docs-design-system with an updated MermaidWrapper component (see https://github.com/interledger/docs-design-system/releases/tag/v0.8.0)
- adjusts the code block background colour on the API pages
Closes https://github.com/interledger/open-payments/issues/552
> Bump dependencies and fix code styles on API pages

- .github/workflows/deploy-docs.yaml
- Updating doc deploy action to checkout submodule
Related to OPE-235
> ci: checkout submodules during doc deploy

- .prettierignore
- package.json
**Description of changes**
This disables prettier formatting of code blocks in markdown to allow us to preserve extra lines like this:
```ts
function something() {
// need extra white space
// like this
}
```
The other options would be to ignore the specific code blocks. Can switch to that if we miss the formatting.
Note that this technically isn't just limited to markdown codeblocks. It would also turn off formatting for, html tagged templates in .js files, for example. I dont think we'll run into that or similar scenario but if we did we could narrow the rule to `.md` files.
**Required**
**Conditional**
> chore: disable codeblock formatting
