interledger/open-payments

documentation/docs/charges.mdx, documentation/docs/discovery.mdx, documentation/docs/invoices.mdx, documentation/docs/mandates.mdx, documentation/docs/wallet-app.mdx, documentation/docs/wallet-wallet.mdx
Fixes to some minor cosmetic issues plus a couple of broken links.
=> minor cosmetic fixes + broken links

documentation/docs/3ppi.mdx, documentation/docs/charges.mdx, documentation/docs/checkout_push.mdx, documentation/docs/invoices.mdx, documentation/docs/mandates.mdx, documentation/docs/p2p.mdx, documentation/docs/recurring.mdx
Updates Invoices, Mandates, and Charges pages, as well as the Use Cases pages with the new APIs presented in last week's community call.
=> Update API pages

open-api-spec.yaml
Adds parameters for pagination on list endpoints
Updates examples
=> feat: pagination, update examples

open-api-spec.yaml
- rename `amount` -> `value`
- make `value` of type string with regex
- make `assetCode` and `assetScale` required
- add `createdAt` and `updatedAt` to incoming and outgoing payment GET response
- fix outgoing payment PUT
=> chore: updating as discussed

auth-server-open-api-spec.yaml
following the [GNAP resource server spec](https://datatracker.ietf.org/doc/html/draft-ietf-gnap-resource-servers-01#section-3.3)
=> fix: token introspection

auth-server-open-api-spec.yaml
closes #103 
Additinally, adds `id` parameter for token endpoints.
=> chore(auth): update grant access information

open-api-spec.yaml
Remove Outgoing Payment authorization and update.
=> feat: add quotes

auth-server-open-api-spec.yaml, open-api-spec.yaml
=> fix: add contact details and tags

.github/workflows/docs2readme.yaml
fixes #117 
Sync open api spec files via github actions
=> feat: add github action to sync open api docs

open-api-spec.yaml
- fixes https://github.com/interledger/open-payments/issues/104
=> chore: add /complete endpoint and completed flag

auth-server-open-api-spec.yaml
=> chore: add receiver to auth server spec

open-api-spec.yaml
- update [`pagination`](https://relay.dev/graphql/connections.htm#sec-undefined.PageInfo.Fields) list response field:
- makes properties required
- remove `first`/`last`
- update [pagination](https://relay.dev/graphql/connections.htm#sec-Arguments) query parameters
- enforce mutually exclusive forward/backward pagination parameters
- ~replace `cursor` with explicit `before`/`after`~
=> fix: change list responses from array to object

auth-server-open-api-spec.yaml
- mark required response fields as such
- remove 404 response from token revocation request
=> chore: specify required fields in responses

.github/workflows/deploy-landing.yaml, .github/workflows/openapi.yaml, .github/workflows/publish-as-api-to-readme-io.yaml, .github/workflows/publish-rs-api-to-readme-io.yaml
Actions weren't running since `master` was changed to `main`
=> fix: change GitHub actions to use main branch

open-api-spec.yaml
Min, max, and default values should be business logic.
=> feat(OP-spec): remove min, max, default on pagination parameters

open-api-spec.yaml
=> chore: enforce connection inclusion in incoming payments

open-api-spec.yaml
https://interledger.org/rfcs/0015-ilp-addresses/#address-requirements
=> chore: specify ILP address requirements

auth-server-open-api-spec.yaml
fixes #157 
fixes #162 
fixes #164 
fixes #165 
fixes #166 
fixes #167
=> feat(auth-spec): grant request changes

open-api-spec.yaml
Add assetCode and assetScale schemas.
- fixes #176
=> chore: include asset details in connection

open-api-spec.yaml
First attempt to add the signature headers to the auth'ed endpoints.
=> feat(OP-spec): add signature headers

auth-server-open-api-spec.yaml
- fixes https://github.com/interledger/open-payments/issues/171
=> chore: enforce one access type per grant

open-api-spec.yaml
=> chore: enforce base64 url-encoded sharedSecret

openapi/auth-server.yaml
- related to https://github.com/interledger/rafiki/issues/749#issuecomment-1318671154
=> chore: disallow additionalProperties in access_token

openapi/auth-server.yaml
- fix delete grant request status code
- add missing error status codes
- fixes #237
=> chore(spec): update status codes

.changeset/strange-toys-wait.md, packages/http-signature-utils/README.md, packages/http-signature-utils/package.json, packages/open-payments/README.md, packages/open-payments/package.json, packages/openapi/README.md, packages/openapi/package.json
- Updating READMEs in the packages
In addition, testing if automatic publishing of packages works:
- https://github.com/interledger/open-payments/pull/251
=> Update package READMEs

README.md
- adds details about how to join the OP catchup call to the readme
=> docs: add details for open payments catchup call

docs/package.json
Adds `private: true` to docs `package.json` so we prevent attempts from publishing it to npm:
https://github.com/interledger/open-payments/actions/runs/6341816617
=> chore: add private: true to docs folder

openapi/resource-server.yaml
- adds the `.well-known/pay` url back
- fixes https://github.com/interledger/open-payments/issues/312
=> fix(open-payments): return erroneously removed url

openapi/auth-server.yaml, openapi/resource-server.yaml, openapi/schemas.yaml
- changed `rafiki.money/auth` to `auth.rafiki.money`
- changed `rafiki.money` to `ilp.rafiki.money`
Fixes https://github.com/interledger/open-payments/issues/316
=> refactor: server urls to correct testnet urls

.changeset/lovely-feet-dance.md, openapi/resource-server.yaml, packages/openapi/src/middleware.test.ts
Matches what we had before the connection -> payment methods changes that works with our jest openapi checks.
- fixes: #330
=> fix(openapi): remove additional properties

openapi/resource-server.yaml, packages/open-payments/src/openapi/generated/resource-server-types.ts
=> allow additional properties in wallet address response

.changeset/neat-items-speak.md, openapi/resource-server.yaml, packages/open-payments/src/openapi/generated/resource-server-types.ts
This fixes validation error and warnings.
When @huijing parsed the spec, she picked up a validation error that our GH workflow did not pick up.
=> fix: resource server spec

docs/src/content/docs/index.mdx, docs/src/partials/testnet-wallet-keys.mdx
Removed the cards on index page. API reference card removed until sidenav works in spec docs. contribute card removed because it's a duplicate of the "View on GitHub" link and seemed excessive without the API reference card.
Also made minor content update to one snippet prereq partial.
=> docs: snippet prereq and index updates

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature-or-feature-subtask.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/code_of_conduct.md, .github/contributing.md, .github/pull_request_template.md, .github/workflows/test-docs-build.yml, README.md, docs/package.json, pnpm-lock.yaml
This PR applies the style of contributing guidelines and documentation we have in Testnet and Rafiki to the Open Payments repository as well.
We like consistency.
=> chore: update contribution documentation

docs/astro.config.mjs, docs/src/content/docs/guides/create-interactive-grant.mdx, docs/src/content/docs/introduction/grants.mdx, docs/src/content/docs/snippets/grant-continue.mdx, docs/src/content/docs/snippets/grant-create.mdx, docs/src/content/docs/snippets/grant-revoke.mdx, docs/src/drafts/guides/create-interactive-grant.mdx
- Added guide for creating an interactive grant
- Updated contextual info in grant-related snippet docs
- Updated GNAP concept page
=> docs: interactive grant guide, misc grant-related updates

docs/astro.config.mjs, docs/src/content/docs/guides/make-onetime-payment.mdx
=> Make one-time payment guide

docs/astro.config.mjs, docs/src/content/docs/guides/make-recurring-payments.mdx, docs/src/content/docs/snippets/quote-create.mdx
=> mi-quote-create-debit-receive-amount

docs/src/content/docs/introduction/op-concepts.mdx, docs/src/content/docs/snippets/quote-create.mdx
Minor updates for creating quote snippets
=> docs: minor updates for quotes

docs/astro.config.mjs
Manually added API section in sidebar, added groups and badges
=> docs: api spec sidebar changes

.changeset/six-planets-walk.md, packages/open-payments/src/client/grant.test.ts, packages/open-payments/src/client/grant.ts, packages/open-payments/src/client/incoming-payment.test.ts, packages/open-payments/src/client/incoming-payment.ts, packages/open-payments/src/client/index.ts, packages/open-payments/src/client/outgoing-payment.test.ts, packages/open-payments/src/client/outgoing-payment.ts, packages/open-payments/src/client/quote.test.ts, packages/open-payments/src/client/quote.ts, packages/open-payments/src/client/requests.test.ts, packages/open-payments/src/client/token.test.ts, packages/open-payments/src/client/token.ts, packages/open-payments/src/client/wallet-address.test.ts, packages/open-payments/src/client/wallet-address.ts, packages/open-payments/src/test/helpers.ts
=> fix: add the `useHttp` option to the missing places

docs/astro.config.mjs
Updated resource server and auth server "books" in TOC to collapsed: true.
=> docs: update toc collapse settings

docs/src/content/docs/introduction/op-concepts.mdx, docs/src/content/docs/resources/op-wallets.mdx, docs/src/content/docs/snippets/before-you-begin.mdx, docs/src/partials/before-you-begin.mdx
Minor content updates to resolve various notes and to-do lists I have on my desk
=> docs: general updates

.changeset/config.json, .changeset/dry-impalas-attack.md, .changeset/twelve-ghosts-serve.md, docs/src/content/docs/guides/make-onetime-payment.mdx, packages/http-signature-utils/README.md, packages/open-payments/README.md, packages/open-payments/src/client/index.ts
- Updating READMEs with new links for the http-sig and open-payments libraries
- Fixing doc formatting on one-time-payment page
Fixes #401
=> chore: update outdated links

docs/src/content/docs/introduction/grants.mdx, docs/src/content/docs/introduction/op-concepts.mdx
=> docs: updates to quotes and int. grants docs

docs/src/content/docs/introduction/grants.mdx, docs/src/content/docs/introduction/op-flow.mdx, docs/src/partials/diagram-interactive-grant.mdx
Made a number of updates based on #338.
* Added view flows for account details and transaction history
* Specified payer/payee in the sequence diagrams
* Made the existing interactive grant sequence diagram into a partial so it could be called by both the OP Flow and GNAP pages
* Updated some of the section titles
=> docs: Some updates for issue #338

docs/src/content/docs/guides/create-interactive-grant.mdx, docs/src/partials/http-msg-sig-note.mdx
Add partial to interactive grant request guide
=> docs: create new partial for http sig

.github/CODEOWNERS
Add Melissa and Mohammed to be codeowners of the markdown documentation files.
=> chore: add codeowner file

docs/astro.config.mjs, docs/package.json, pnpm-lock.yaml
- This PR updates dependencies to the latest versions, which finally resolves the sidebar problem
Closes #351 
Closes #388
=> chore: bump dependencies to latest version

.changeset/red-bulldogs-type.md, openapi/auth-server.yaml, packages/open-payments/src/openapi/generated/auth-server-types.ts
Apparently, my tool did some formatting changes, too. Sorry!
- fixes #433
=> fix: make interact_ref non required

docs/src/content/docs/guides/create-interactive-grant.mdx
=> docs: resolves #438

docs/src/content/docs/introduction/op-concepts.mdx, docs/src/content/docs/introduction/op-flow.mdx
=> Add section on Payment Methods to Concepts

package.json
Fix changeset publish by using `pnpm publish -r` as stated in the PNPM documentation: 
https://pnpm.io/using-changesets
Fixes #462
=> chore(ci): try to fix changeset package publish

docs/src/content/docs/introduction/op-concepts.mdx, docs/src/content/docs/introduction/op-flow.mdx
Mohammed is on vacation this week. This PR is for minor changes related to some work he did last week and to incorporate a suggestion by Sabine.
=> minor updates

.github/workflows/deploy-docs.yaml, .github/workflows/env-setup/action.yaml, .github/workflows/test-docs-build.yml, .nvmrc, README.md, package.json, packages/http-signature-utils/package.json, packages/open-payments/package.json, pnpm-lock.yaml
- Use Node 20 by specifiying `.nvm` file
- Update Readme
Fixes #459
=> chore: use node 20

docs/astro.config.mjs, docs/package.json, docs/src/content/docs/introduction/op-concepts.mdx, pnpm-lock.yaml
- Add [starlight-links-validator](https://github.com/HiDeoo/starlight-links-validator) package to our docs package (to prevent doc builds with broken links)
- Fix all broken internal links
Fixes #476
=> feat: add starlight links validator

docs/src/content/docs/resources/op-wallets.mdx
Added wallet information and external links for both Fynbos and GateHub
https://github.com/interledger/open-payments/issues/492
=> Docs update - adding info and links for Fynbos and GateHub

.github/workflows/add_to_docs_board.yml
Action to add issues with `user-docs` label automatically to the Documentation board
Fixes #502
=> feat(ci): add action to add to docs project

docs/src/content/docs/guides/create-interactive-grant.mdx, docs/src/content/docs/resources/op-wallets.mdx, docs/src/content/docs/snippets/before-you-begin.mdx, docs/src/partials/before-you-begin.mdx
Adding preliminary changes to the test wallet instructions. Copy is not final by any means, just wanted to update for the hackathon so people are not confused. Screenshots from rafiki.money are removed until new ones are added.
Part of #509
[Deploy preview](https://deploy-preview-510--openpayments-preview.netlify.app/snippets/before-you-begin/)
=> docs: preliminary test wallet updates

docs/src/content/docs/introduction/client-keys.mdx, docs/src/content/docs/introduction/http-signatures.mdx
Updates made to support Rafiki doc issue #2966
=> docs: client key updates

docs/package.json, pnpm-lock.yaml
Updating dependencies for the docs.
=> chore: routine dependency bumps

openapi/auth-server.yaml, openapi/resource-server.yaml, openapi/schemas.yaml, openapi/wallet-address-server.yaml
Update rafiki.money references to new test wallet URL
=> docs: fixes #514

docs/package.json, docs/src/components/ChunkedSnippet.astro, pnpm-lock.yaml
This PR updates the `<ChunkedSnippet>` component to have a copy button.
Closes #384
=> feat: add copy button for ChunkedSnippet component

docs/src/content/docs/introduction/overview.mdx
Added use case section to overview page.  Will link to remaining guides as they become available.
=> docs: mi/170/add-use-cases

docs/src/content/docs/resources/glossary.mdx
Added an Open Payments-specific payment pointer entry in the glossary.
=> docs: mi/539/payment-pointer-glossary

docs/astro.config.mjs, docs/src/content/docs/resources/further-learning.mdx
Added further learning page under Resources.
=> docs: mi/537/further-learning

docs/src/content/docs/guides/create-interactive-grant.mdx, docs/src/content/docs/introduction/op-flow.mdx, docs/src/content/docs/snippets/grant-continue.mdx, docs/src/content/docs/snippets/grant-create.mdx
Included the following content updates:
- **Open Payments flow** page
-  Added a note about the timing of a continue request
- **Create a grant request** code snippets page
-  Added a note about the purpose of the continue object
- **Continue a grant request** code snippets page
-  Added a note about the timing of a continue request
- **Create an interactive grant** guide
-  Added a note about the timing of a continue request
- Added content around the purpose of the continue object
Fixes https://github.com/interledger/open-payments/issues/541 and https://github.com/interledger/open-payments/issues/543
=> docs: content updates and clarifications

docs/src/content/docs/snippets/before-you-begin.mdx
=> docs: fixes #563

docs/src/content/docs/introduction/client-keys.mdx
also changed the formatting of some code blocks
=> docs: sequence diagram update

docs/src/content/docs/introduction/hash-verification.mdx, docs/src/content/docs/introduction/idp.mdx
fixes #572
Also updated has verification overview with an extra detail from Max
=> docs: fix broken link

docs/astro.config.mjs, docs/package.json, docs/src/components/Header.astro, docs/src/components/PageSidebar.astro, pnpm-lock.yaml
* keeping in line with Starlight breaking changes in v0.32.0
=> chore: docs dependency updates

docs/src/content/docs/introduction/http-signatures.mdx
added wrap to two code blocks on http signatures page
=> docs: add wrap to code blocks

.github/CODEOWNERS
Add @brad-dow  as codeowner for docs
=> chore: add brad-dow as codeowner for docs

docs/astro.config.mjs, docs/package.json, pnpm-lock.yaml
This PR bumps docs dependencies to the latest versions and adds the starlight-fullview-mode plugin.
See https://github.com/interledger/docs-design-system/issues/41
=> feat: add starlight-fullview-mode plugin

docs/astro.config.mjs
=> docs: section name change

docs/src/content/docs/snippets/grant-create.mdx
Cares for the majority of #585 . What's not covered in this PR will be covered when we work on #600 .
=> docs: Update info in create grant snippet page

docs/package.json, pnpm-lock.yaml
Starlight upgrade caused our code block styling to break. Doing a rollback of Starlight and Starlight OpenApi till we can address this.
=> fit: starlight roll back due to code stykle breaks

docs/astro.config.mjs
=> docs: added redirect to astro config

docs/src/content/docs/sdk/grant-create-outgoing.mdx, docs/src/content/docs/sdk/incoming-get.mdx
https://github.com/interledger/open-payments-snippets/issues/57
=> fixes ts snippet repo issue 57

docs/astro.config.mjs, docs/src/content/docs/guides/outgoing-grant-future-payments.mdx, docs/src/content/docs/guides/split-payments.mdx
outgoing-grant: removed snippets, changed some wording, updated some code examples, added links to API docs.
split-payments: made a lot of content revisions based on an updated understanding of what's going on, removed snippets, updated code examples, added links to API docs.
=> docs: outgoing and split guide updates

.github/PULL_REQUEST_TEMPLATE/doc_template.md, .github/PULL_REQUEST_TEMPLATE/eng_template.md, .github/pull_request_template.md
Created documentation PR template. Moved existing PR template text to new eng_template file.
=> add doc pr template

.gitmodules
**Description of changes**
**Required**
**Conditional**
=> chore: use HTTP for open-payments-specification submodule

docs/src/content/docs/guides/make-onetime-payment.mdx, docs/src/content/docs/sdk/before-you-begin.mdx
Stopgap updates to OTP guide to help upcoming hackathon participants. More significant updates are coming in the next few weeks.
**Description of changes**
**Required**
**Conditional**
=> docs: otp guide updates

docs/src/content/docs/guides/outgoing-grant-future-payments.mdx, docs/src/content/docs/sdk/before-you-begin.mdx, docs/src/partials/interaction-required.mdx
Update guide to more closely follow the new format introduced with the Split Payment guide revisions.
Summary:
* Revised intro
* Added Scenario heading
* Removed Dependencies section
* Other wording updates
* Added example responses
* Minor updates to some existing TS examples
**Required**
**Conditional**
=> docs: fixes #681
